#!/bin/sh


if [ $# != 1 ]; then
    echo "Usage: $0 prepare|perform"
    exit 1
fi


function getVersionToRelease {
    CURRENT_VERSION=`mvn ${MVN_ARGS} org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v "\[INFO\]"`
    echo ${CURRENT_VERSION%%-SNAPSHOT}
}

function getBranch {
    git symbolic-ref --short HEAD
}

ls
case $1 in
prepare)        
    VERSION=$(getVersionToRelease)
    RELEASE_BRANCH="release/$VERSION"        
    git checkout -b ${RELEASE_BRANCH} || exit 1
    echo $VERSION > .version
    git add .version
    git push origin ${RELEASE_BRANCH} || exit 1
    git checkout develop
    echo "Branch $RELEASE_BRANCH is ready"
    ;;
perform)    
    if [ $(hostname) != "btrp" ]; then
            echo "This script must be executed on btrp.inria.fr"
            exit 1
    fi    
    VERSION=$(cat .version)
    #Code update and maven release process
    echo "-- Bump the code version to $VERSION --"
    ./bump_release.sh code $VERSION || exit 1
    git commit -m "Bump the code to version $VERSION" -a
    
    echo "-- Prepare the release --"
    mvn -B release:prepare || exit 1

    echo "-- Push the changes and the tags --"
    git push origin
    git push origin --tags

    echo "-- Perform the release --"
    mvn release:perform || exit 1

    #We generate the big javadoc and put it on the webserver
    echo "-- Generate the Javadoc --"
    mvn javadoc:aggregate > /dev/null
    APIDOC_ROOT="/usr/share/nginx/html/apidocs/releases/btrplace/solver/"
    mkdir -p $APIDOC_ROOT > /dev/null
    mv target/apidoc ${APIDOC_ROOT}/${VERSION}
    
    # merge the version changes back into develop so that folks are working against the new release 
    echo "-- Integrate the next version into the develop branch --"
    git checkout develop
    git merge --no-ff -m "integrate the next version generated by maven" release/$VERSION || exit 1
 
    # housekeeping -- rewind the release branch by one commit to fix its version at $VERSION
    #   excuse the force push, it's because maven will have already pushed the next dev version
    #   to origin with this branch, and I don't want that version (or a diverging revert commit)
    #   in the release or master branches.
    echo "-- Remove the next version from the release branch --"
    git checkout release/$VERSION
    git reset --hard HEAD~1 || exit 1
    git push --force origin release/$VERSION || exit 1
 
    # finally, if & when the code gets deployed to production
    echo "-- Integrate the release into the master branch --"
    git checkout master || exit 1
    git merge --no-ff -m "integrate the release" release/$VERSION
#    git branch -d release/$VERSION || exit 1
    git push
#    git push origin :release/$VERSION

    echo "-- Notify the website for the release --"
    ./bump_release.sh site ${VERSION}
    ;;
esac